package com.mutu.spring.rest.zgen.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.mutu.spring.rest.zgen.entity.UserRolesExample;
import com.mutu.spring.rest.zgen.entity.UserRolesKey;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int insert(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int insertSelective(UserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    List<UserRolesKey> selectByExampleWithRowbounds(UserRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    List<UserRolesKey> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLES
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRolesKey record, @Param("example") UserRolesExample example);
}