package com.mutu.spring.rest.zgen.entity;

public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.USER_ID
	 *
	 * @mbggenerated
	 */
	private Long userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.USERNAME
	 *
	 * @mbggenerated
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column USER.PASSWORD
	 *
	 * @mbggenerated
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.USER_ID
	 *
	 * @return the value of USER.USER_ID
	 *
	 * @mbggenerated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.USER_ID
	 *
	 * @param userId the value for USER.USER_ID
	 *
	 * @mbggenerated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.USERNAME
	 *
	 * @return the value of USER.USERNAME
	 *
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.USERNAME
	 *
	 * @param username the value for USER.USERNAME
	 *
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column USER.PASSWORD
	 *
	 * @return the value of USER.PASSWORD
	 *
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column USER.PASSWORD
	 *
	 * @param password the value for USER.PASSWORD
	 *
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table USER
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", userId=").append(userId);
		sb.append(", username=").append(username);
		sb.append(", password=").append(password);
		sb.append("]");
		return sb.toString();
	}
}